dist: trusty

os:
- linux

language: go

go:
- "1.14"
- tip

env:
- GO111MODULE: "on"
  secure: hBv065YecCQnFxj4rRIBmEOwofSV/Tz5f/ol6ThrY9/w7G7DTe/L8qYds7tyaLfn8z6xH60BHqkvG9/kfFUYP4tKvfp9d0JREOAl1T1ouy8DyAWlfVu81DfTlcFywLiK7gQjlljl+mcJ8FpRHo/HWqREKqFFgRzGf6Cnr0uHM11BHp4liGRBkKzxtpeCssUiro03PyH1WRP2N1eWh0Gxk1GdZY1v3wCFSfiPKhIDo2Eks1mW6nQdPG9DK6WAGrJ/I1aBoYfGgxZUTxXdesoZn2gh5r10HEdWKvOJpOsHz73grkIXLgYQhtQHywdwI4CmpF9+MgLWn7p2ZLou//UuO4OHQA9IP9Dd/mi5+dFHOGFyd7uny34iWZzYP1V0qZehbCuCGLU90ar+7XNOo17JDY3zVhCjscE8oJVZeczg+cMTVAkAV/YcfVvMA6vEGlDwbR60dRfgR/W5tlkpVdeiFM2I2AmcRqEVobGzMQnTLx1yu/7Pse8pTPxKbm67HB1ah5Gbp3Sh7QX2OPPZqSx/fV6z4puStBHQNtPJluGmUjNHAK+np5JIoWaHreJKne49jHMboGh3pkqNifMwJDdcbR9cMpkoVnGDFXT5rXlObrROrlupQeRpXMlrlA9MHEE9raXYVJmI/cJdRWnBKqFnkdqWte2bwLoy3U2C5QuK2T8=

install:
- go get github.com/mfridman/tparse
- go get github.com/mattn/goveralls
- go get github.com/lawrencewoodman/roveralls

script:
- make check
- make coveralls
